log_format custom_log '$remote_addr $http_x_forwarded_for - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$uri"';

log_format custom_debug '$remote_addr - $remote_user [$time_local] "$request"'
'http_cf_ipcountry=$http_cf_ipcountry endpoint=$endpoint uri=$uri block=$block';
