location / {
    add_header X-Frame-Options "ALLOWALL";
    try_files $uri $uri/ /index.html;
    root /var/www/upload;
}

location /api/ {
    client_max_body_size 50m;
    proxy_pass http://127.23.12.17:8080/api/;
}
