server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name groq.moonchan.xyz;

    include /etc/nginx/conf.d/ssl/moonchan.xyz.conf;

    include /etc/nginx/sites-available/groq.conf;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name siliconflow.moonchan.xyz;

    include /etc/nginx/conf.d/ssl/moonchan.xyz.conf;

    include /etc/nginx/sites-available/siliconflow.conf;
}