# 1. 在 http 级别定义 upstream
upstream shijima {
    server 127.25.5.19:8080;

    # 连接池中保持的空闲长连接最大数量
    keepalive 32;

    # 建议设置长连接超时时间，略小于后端的 keepalive 超时
    keepalive_timeout 60s;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name moonchan.xyz c.moonchan.xyz cloudcone.moonchan.xyz vps.moonchan.xyz;
    server_name 810114.xyz nmbyd2.top nmbyd3.top nmbyd4.top nmbyd5.top;

    # ssl configuration
    include /etc/nginx/conf.d/ssl/moonchan.xyz.conf;

    access_log /dev/null;
    error_log /dev/null;

    #include /etc/nginx/conf.d/addon/general-deny.conf;

    # 精确匹配路径 /go/
    location = /go/ {
        return 302 https://moonchan.xyz/;
    }

    include /etc/nginx/conf.d/addon/3x-ui.conf;

    location /api/ {
        add_header X-Frame-Options "ALLOWALL";
        proxy_pass http://shijima;

        # 3. 开启 HTTP/1.1 (Keep-Alive 必备)
        proxy_http_version 1.1;

        # 4. 清除 Connection 头部
        proxy_set_header Connection "";

        # 5. 建议配置的通用头部
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # 如果后端需要知道原始协议 (http/https)
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /var/www/moonchan;
    }

    # /ws /chat
    include /etc/nginx/conf.d/addon/qwen.conf;


    include /etc/nginx/conf.d/addon/doh.conf;
    include /etc/nginx/conf.d/addon/v2ray.conf;

    # redirect server error pages to the static page /50x.html
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}


server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name moonchan.publicvm.com;

    # ssl configuration
    include /etc/nginx/conf.d/ssl/free_dns.conf;

    access_log /dev/null;
    error_log /dev/null;

    #include /etc/nginx/conf.d/addon/general-deny.conf;

    include /etc/nginx/conf.d/addon/3x-ui.conf;

    location /api/ {
        add_header X-Frame-Options "ALLOWALL";
        proxy_pass http://shijima;

        # 3. 开启 HTTP/1.1 (Keep-Alive 必备)
        proxy_http_version 1.1;

        # 4. 清除 Connection 头部
        proxy_set_header Connection "";

        # 5. 建议配置的通用头部
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # 如果后端需要知道原始协议 (http/https)
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /var/www/moonchan;
    }

    # /ws /chat
    include /etc/nginx/conf.d/addon/qwen.conf;

    include /etc/nginx/conf.d/addon/doh.conf;
    include /etc/nginx/conf.d/addon/v2ray.conf;

    # redirect server error pages to the static page /50x.html
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}

