upstream nyaa {
    server 127.25.23.4:8080;

    # 保持 32 个长连接
    keepalive 32;
}

server {
    listen 443 ssl http2;
    server_name nyaa.moonchan.xyz nyaa.810114.xyz nyaa.nmbyd2.top nyaa.nmbyd3.top nyaa.nmbyd4.top;

    # ssl configuration
    include /etc/nginx/conf.d/ssl/moonchan.xyz.conf;

    access_log /dev/null;
    error_log /dev/null;

    location / {
        client_max_body_size 50m;

        # 1. 必须指向 upstream 的名称
        proxy_pass http://nyaa;

        # 2. 必须设置 HTTP/1.1 协议（keepalive 必须）
        proxy_http_version 1.1;

        # 3. 清除 Connection 头部（允许长连接传递）
        proxy_set_header Connection "";

        # 4. 建议传递真实的 Host 和 IP
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

upstream sukebei {
    server 127.25.23.5:8080;

    # 保持 32 个长连接
    keepalive 32;
}

server {
    listen 443 ssl http2;
    server_name sukebei.moonchan.xyz sukebei.810114.xyz sukebei.nmbyd2.top sukebei.nmbyd3.top sukebei.nmbyd4.top;
    server_name skb.moonchan.xyz skp.moonchan.xyz;

    # ssl configuration
    include /etc/nginx/conf.d/ssl/moonchan.xyz.conf;

    access_log /dev/null;
    error_log /dev/null;

    location / {
        client_max_body_size 50m;

        # 1. 必须指向 upstream 的名称
        proxy_pass http://sukebei;

        # 2. 必须设置 HTTP/1.1 协议（keepalive 必须）
        proxy_http_version 1.1;

        # 3. 清除 Connection 头部（允许长连接传递）
        proxy_set_header Connection "";

        # 4. 建议传递真实的 Host 和 IP
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}