server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name sukebei.moonchan.xyz skb.moonchan.xyz;
    include /etc/nginx/conf.d/ssl/moonchan.xyz.conf;
    include /etc/nginx/snippets/doh.conf;
    include /etc/nginx/snippets/v2ray.conf;
    include /etc/nginx/sites-available/route/sukebei.conf;
    access_log off;
    error_log /dev/null;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name sukebei.nmbyd2.top sukebei.nmbyd3.top sukebei.nmbyd4.top skb.nmbyd2.top skb.nmbyd3.top skb.nmbyd4.top;
    include /etc/nginx/conf.d/ssl/nmbyd.top.conf;
    include /etc/nginx/snippets/doh.conf;
    include /etc/nginx/snippets/v2ray.conf;
    include /etc/nginx/sites-available/route/sukebei.conf;
    access_log off;
    error_log /dev/null;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name sukebei.810114.xyz skb.810114.xyz;
    include /etc/nginx/conf.d/ssl/810114.xyz.conf;
    include /etc/nginx/snippets/doh.conf;
    include /etc/nginx/snippets/v2ray.conf;
    include /etc/nginx/sites-available/route/sukebei.conf;
    access_log off;
    error_log /dev/null;
}
