server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name moonchan.xyz vps.moonchan.xyz 810114.xyz nmbyd2.top nmbyd3.top nmbyd4.top nmbyd5.top nmbyd6.top nmbyd7.top nmbyd8.top;
    include /etc/nginx/conf.d/ssl/moonchan.xyz.conf;
    include /etc/nginx/conf.d/addon/doh.conf;
    include /etc/nginx/conf.d/addon/v2ray.conf;
    include /etc/nginx/sites-available/routes/route-moonchan.conf;
    error_log /dev/null;
}
