server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name upload.moonchan.xyz;
    include /etc/nginx/conf.d/ssl/moonchan.xyz.conf;
    include /etc/nginx/snippets/doh.conf;
    include /etc/nginx/snippets/v2ray.conf;

    client_body_timeout 300s;
    include /etc/nginx/sites-available/route/upload.conf;

    access_log off;
    error_log /dev/null;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name upload.810114.xyz;
    include /etc/nginx/conf.d/ssl/810114.xyz.conf;
    include /etc/nginx/snippets/doh.conf;
    include /etc/nginx/snippets/v2ray.conf;

    client_body_timeout 300s;
    include /etc/nginx/sites-available/route/upload.conf;

    access_log off;
    error_log /dev/null;
}
