server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name proxy.moonchan.xyz proxy.810114.xyz proxy.nmbyd2.top proxy.nmbyd3.top proxy.nmbyd4.top;
    include /etc/nginx/conf.d/ssl/moonchan.xyz.conf;
    include /etc/nginx/snippets/doh.conf;
    include /etc/nginx/snippets/v2ray.conf;
    include /etc/nginx/sites-available/proxy.conf;
    access_log off;
    error_log /dev/null;
}
