server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name nyaa.moonchan.xyz;
    include /etc/nginx/conf.d/ssl/moonchan.xyz.conf;
    include /etc/nginx/snippets/doh.conf;
    include /etc/nginx/snippets/v2ray.conf;
    include /etc/nginx/sites-available/nyaa.conf;
    access_log off;
    error_log /dev/null;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name nyaa.nmbyd2.top nyaa.nmbyd3.top nyaa.nmbyd4.top;
    include /etc/nginx/conf.d/ssl/nmbyd.top.conf;
    include /etc/nginx/snippets/doh.conf;
    include /etc/nginx/snippets/v2ray.conf;
    include /etc/nginx/sites-available/nyaa.conf;
    access_log off;
    error_log /dev/null;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name nyaa.810114.xyz;
    include /etc/nginx/conf.d/ssl/810114.xyz.conf;
    include /etc/nginx/snippets/doh.conf;
    include /etc/nginx/snippets/v2ray.conf;
    include /etc/nginx/sites-available/nyaa.conf;
    access_log off;
    error_log /dev/null;
}
