
map $http_x_cf_ipcountry $block {
    'CN'     0;
    ''       0;
    default  $endpoint;
}

map $uri $endpoint {
    /ame/    1;
    /ame     1;
    default  0;
}

#if ($block) { return 403; }
