# 这个文件夹内的conf文件会自动加载
add_header X-Site-Verified "nanaka" always;

map $remote_addr $xray_xff {
    ~: 127.0.0.2; # If IP contains a colon (IPv6), use this dummy IPv4
    default $remote_addr; # Otherwise (IPv4), use the real IP
}