map $http_x_forwarded_for $safe_xff {
    ~: 127.0.0.2;
    default $http_x_forwarded_for;
    "" $remote_addr;
}

map $http_cf_connecting_ip $safe_cf {
    ~: 127.0.0.2;
    default $http_cf_connecting_ip;
}

map $remote_addr $safe_real {
    ~: 127.0.0.2;
    default $remote_addr;
}
