# 这个文件夹内的conf文件会自动加载
add_header X-Site-Verified "nanaka" always;

# 1. Scrub the incoming X-Forwarded-For header
map $http_x_forwarded_for $safe_xff {
    ~: 127.0.0.2; # If it has a colon (IPv6), fake it to 127.0.0.2
    default $http_x_forwarded_for; # If IPv4, leave it alone
    "" $remote_addr; # Fallback
}

# 2. Scrub Cloudflare's specific IP header
map $http_cf_connecting_ip $safe_cf {
    ~: 127.0.0.2;
    default $http_cf_connecting_ip;
}

# 3. Scrub the direct TCP connection IP
map $remote_addr $safe_real {
    ~: 127.0.0.2;
    default $remote_addr;
}