upstream groq_backend {
    server 127.25.2.9:8080;
}

upstream siliconflow_backend {
    server 127.26.3.5:8080;
}

upstream twitter_backend {
    server 127.25.9.21:8080;
    keepalive 32;                  # 设置连接池大小（空闲保持的连接数）
    keepalive_timeout 60s;          # 空闲连接的超时时间
    keepalive_requests 1000;        # 单个连接上最多处理的请求数
}

upstream twimg_backend {
    server 127.25.9.15:8080;
    keepalive 16;
    keepalive_timeout 60s;
    keepalive_requests 1000;
}