upstream twitter_backend {
    server 127.25.9.21:8080;
    keepalive 32;                  # 设置连接池大小（空闲保持的连接数）
    keepalive_timeout 60s;          # 空闲连接的超时时间
    keepalive_requests 1000;        # 单个连接上最多处理的请求数
}

upstream twimg_backend {
    server 127.25.9.15:8080;
    keepalive 16;
    keepalive_timeout 60s;
    keepalive_requests 1000;
}

upstream ex_backend {
    server 127.25.23.2:8080;
    keepalive 32;
    keepalive_timeout 6s;
    keepalive_requests 1000;
}

upstream ehgt_backend {
    server 127.26.5.13:8080;
    keepalive 32;
    keepalive_timeout 6s;
    keepalive_requests 1000;
}

# 定义 Cloudflare DoH 的上游
upstream cloudflare_doh {
    server cloudflare-dns.com:443;
    # 保持连接数，根据并发量调整，通常 16-32 足够
    keepalive 32;
}

# pximg - Pixiv image proxy
upstream pximg {
    server 127.25.9.16:8080;
    keepalive 32;
}

# proxy - Generic proxy service
upstream proxy {
    server 127.24.11.16:8080;
    keepalive 32;
}

# azure - Upload backend
upstream azure {
    server 127.23.12.17:8080;
    keepalive 32;
}
