location /groq {
    include /etc/nginx/sites-available/groq.conf;
}

location /siliconflow {
    include /etc/nginx/sites-available/siliconflow.conf;
}

location /gemini {
    proxy_pass https://generativelanguage.googleapis.com;
    proxy_set_header Host generativelanguage.googleapis.com;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_buffering off;
    proxy_cache off;
    proxy_ssl_server_name on;
    proxy_ssl_protocols TLSv1.2 TLSv1.3;
}
