location / {
    add_header X-Frame-Options "ALLOWALL";
    root /var/www/moonchan;
}

location = /go/ {
    return 302 https://moonchan.xyz/;
}

location /sub/ {
    proxy_pass http://127.25.12.103:8080/sub/;
    proxy_set_header Host $http_host;
}

location /3x-ui/ {
    proxy_pass http://127.25.12.101:8080/3x-ui/;
    proxy_set_header Host $http_host;
}

location /api/v2/ {
    add_header X-Frame-Options "ALLOWALL";
    proxy_pass http://127.25.5.19:8080/api/v2/;
}

location = /ws/ {
    proxy_redirect off;
    proxy_pass http://127.114.5.14:8080;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
}
