location / {
    proxy_set_header Host $host;
    proxy_pass http://127.25.23.4:8080/;
}

location /static/js/bootstrap-select.min.js {
    alias /var/www/moonchan/static/js/bootstrap-select.min.js;
}
